# Generated by Django 3.0.6 on 2020-05-30 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiply', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericfile',
            name='csv',
            field=models.BooleanField(default=False),
        ),
    ]
