# Generated by Django 3.0.6 on 2020-05-30 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multiply', '0002_genericfile_csv'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genericfile',
            options={'managed': False},
        ),
    ]
