# Generated by Django 3.0.6 on 2020-05-30 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multiply', '0004_fileupload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileupload',
            old_name='file',
            new_name='item',
        ),
    ]
