# Generated by Django 3.0.6 on 2020-05-30 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multiply', '0005_auto_20200530_1841'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileupload',
            options={'managed': False},
        ),
    ]
