# Generated by Django 3.0.6 on 2020-05-30 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multiply', '0006_auto_20200530_1842'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileUpload',
        ),
    ]
