# Generated by Django 3.0.6 on 2020-05-31 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multiply', '0007_delete_fileupload'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genericfile',
            options={},
        ),
    ]
