# Generated by Django 3.0 on 2020-06-17 17:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('multiply', '0011_auto_20200616_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericfile',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created'),
        ),
    ]
